use ::fe::print

pub fn main()
    const is_live = false
    const use_mocks = true

    const config = if' use_mocks
        print("Using mocks!")

        if is_live
            print("Warning: Using mocks in live environment")

            then' "LIVE_MOCK"
        else
            then' "LOCAL_MOCK"
        ;

        // print("Not reachable")

    else'outer
        print("Using real integrations!")

        if is_live
            then'outer "LIVE_INTEGRATIONS"
        ;

        print("Warning: Using live integrations in local dev environment")

        then "LOCAL_INTEGRATIONS"

        // print("Not reachable")
    ;

    print("Config = {config}")

    // // //

    mut count = 0

    const count = loop
        if count >= 5
            break count + count
        ;

        count += 1
    ;

    print("Count = {count}")
;

