use ::fe::print

pub fn main()
    const is_funny = true
    const is_cool = true

    const response = if' is_funny
        print("you're funny ...")

        if is_cool
            print("Wow you're lucky")

            then' "HAHA You're Amazing!"
        else
            then' "hah"
        ;

        // print("Not reachable")

    else
        print("you're not so funny ...")

        const x = if is_cool
            then "Whatevs"
        else
            print("Not so lucky...")

            then "Ew times {42}."
        ;

        then x

        // print("Not reachable")
    ;

    print("\nRESPONSE = {response}")
;

