use ::fe::print

pub fn main()
    // print(repeat("#", 10))

    // print("# Hello! #")

    // print(repeat("#", 10))

    const age = 26
    // const drink = "water"

    const drink = if age >= 19 then "beer" else "juice"

    const drink = if age >= 19
        then "beer"
    else
        then "juice"
    ;

    const drink = if age >= 19
        print("true")
        then "beer"
    else
        print("false")
        then "juice"
    ;

    // const drink = if true
    //     then "beer"
    // else
    //     print("false")
    //     then "juice"
    // ;

    // const drink = if true then "beer" else
    //     print("false")
    //     then "juice"
    // ;

    // const drink = if true
    //     print("true")
    //     then "beer"
    // else 
    //     then "juice"
    // ;

    print(drink)
;

// fn repeat(item: String, n: Int): String
//     mut out = ""
//     mut i = 0

//     while i < n
//         out = "{out}{item}"
//         i += 1
//     ;

//     return out
// ;

